services:
  db-users:
    image: postgres:16.1
    container_name: postgres-avb-users
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=dbuser
      - POSTGRES_DB=users
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  db-companies:
    image: postgres:16.1
    container_name: postgres-avb-companies
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=dbuser
      - POSTGRES_DB=companies
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    container_name: eureka-server
    ports:
      - "8761:8761"

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    depends_on:
      - db-users
      - eureka-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-users:5432/users
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - COMPANY_SERVICE_URL=http://api-gateway:8080/api/companies

  company-service:
    build:
      context: ./company-service
      dockerfile: Dockerfile
    container_name: company-service
    depends_on:
      - db-companies
      - eureka-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-companies:5432/companies
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - USER_SERVICE_URL=http://api-gateway:8080/api/users