user-service.url: http://api-gateway:8080/api/users
server:
  port: 8082
spring:
  application:
    name: company-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6542/companies
    username: dbuser
    password: 12345
  liquibase:
    change-log: classpath:/db/changelog/changelog.yml
    enabled: true
  jpa:
    properties:
      hibernate:
        default_schema: entities
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true