server:
  port: 8082
spring:
  application:
    name: company-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6542/companies
    username: dbuser
    password: 12345
  liquibase:
    change-log: classpath:/db/changelog/changelog.xml
  jpa:
    properties:
      hibernate:
        default_schema: entities