server:
  port: 8081
spring:
  application:
    name: user-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6541/users
    username: dbuser
    password: 12345
  liquibase:
    change-log: classpath:/db/changelog/changelog.xml
  jpa:
    properties:
      hibernate:
        default_schema: entities
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true